package com.prince.myproj.brain.models;

import java.io.Serializable;
import java.util.Date;

public class BrainWordRecordModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_record.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_record.day_index
     *
     * @mbggenerated
     */
    private Integer dayIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_record.now_day
     *
     * @mbggenerated
     */
    private Date nowDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_record.id
     *
     * @return the value of brain_word_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_record.id
     *
     * @param id the value for brain_word_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_record.open_id
     *
     * @return the value of brain_word_record.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_record.open_id
     *
     * @param openId the value for brain_word_record.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_record.day_index
     *
     * @return the value of brain_word_record.day_index
     *
     * @mbggenerated
     */
    public Integer getDayIndex() {
        return dayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_record.day_index
     *
     * @param dayIndex the value for brain_word_record.day_index
     *
     * @mbggenerated
     */
    public void setDayIndex(Integer dayIndex) {
        this.dayIndex = dayIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_record.now_day
     *
     * @return the value of brain_word_record.now_day
     *
     * @mbggenerated
     */
    public Date getNowDay() {
        return nowDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_record.now_day
     *
     * @param nowDay the value for brain_word_record.now_day
     *
     * @mbggenerated
     */
    public void setNowDay(Date nowDay) {
        this.nowDay = nowDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrainWordRecordModel other = (BrainWordRecordModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getDayIndex() == null ? other.getDayIndex() == null : this.getDayIndex().equals(other.getDayIndex()))
            && (this.getNowDay() == null ? other.getNowDay() == null : this.getNowDay().equals(other.getNowDay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getDayIndex() == null) ? 0 : getDayIndex().hashCode());
        result = prime * result + ((getNowDay() == null) ? 0 : getNowDay().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", openId=").append(openId);
        sb.append(", dayIndex=").append(dayIndex);
        sb.append(", nowDay=").append(nowDay);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}