package com.prince.myproj.brain.models;

import java.io.Serializable;

public class BrainSentenceModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_sentence.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_sentence.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_sentence.english
     *
     * @mbggenerated
     */
    private String english;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_sentence.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_sentence.voice
     *
     * @mbggenerated
     */
    private String voice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_sentence.chinese
     *
     * @mbggenerated
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_sentence.id
     *
     * @return the value of brain_sentence.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_sentence.id
     *
     * @param id the value for brain_sentence.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_sentence.key_word
     *
     * @return the value of brain_sentence.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_sentence.key_word
     *
     * @param keyWord the value for brain_sentence.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_sentence.english
     *
     * @return the value of brain_sentence.english
     *
     * @mbggenerated
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_sentence.english
     *
     * @param english the value for brain_sentence.english
     *
     * @mbggenerated
     */
    public void setEnglish(String english) {
        this.english = english == null ? null : english.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_sentence.source
     *
     * @return the value of brain_sentence.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_sentence.source
     *
     * @param source the value for brain_sentence.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_sentence.voice
     *
     * @return the value of brain_sentence.voice
     *
     * @mbggenerated
     */
    public String getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_sentence.voice
     *
     * @param voice the value for brain_sentence.voice
     *
     * @mbggenerated
     */
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_sentence.chinese
     *
     * @return the value of brain_sentence.chinese
     *
     * @mbggenerated
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_sentence.chinese
     *
     * @param chinese the value for brain_sentence.chinese
     *
     * @mbggenerated
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrainSentenceModel other = (BrainSentenceModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKeyWord() == null ? other.getKeyWord() == null : this.getKeyWord().equals(other.getKeyWord()))
            && (this.getEnglish() == null ? other.getEnglish() == null : this.getEnglish().equals(other.getEnglish()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getVoice() == null ? other.getVoice() == null : this.getVoice().equals(other.getVoice()))
            && (this.getChinese() == null ? other.getChinese() == null : this.getChinese().equals(other.getChinese()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKeyWord() == null) ? 0 : getKeyWord().hashCode());
        result = prime * result + ((getEnglish() == null) ? 0 : getEnglish().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getVoice() == null) ? 0 : getVoice().hashCode());
        result = prime * result + ((getChinese() == null) ? 0 : getChinese().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", keyWord=").append(keyWord);
        sb.append(", english=").append(english);
        sb.append(", source=").append(source);
        sb.append(", voice=").append(voice);
        sb.append(", chinese=").append(chinese);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}