package com.prince.myproj.brain.models;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class BrainWordModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.exchange
     *
     * @mbggenerated
     */
    private String exchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.voice
     *
     * @mbggenerated
     */
    private String voice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.times
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.cet4
     *
     * @mbggenerated
     */
    private Integer cet4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.cet6
     *
     * @mbggenerated
     */
    private Integer cet6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_words.gre
     *
     * @mbggenerated
     */
    private Integer gre;


    private List<BrainSentenceModel> brainSentenceModels;

    public void addBrainSentenceModel(BrainSentenceModel brainSentenceModel){
        if(brainSentenceModels==null){
            brainSentenceModels = new ArrayList<BrainSentenceModel>();
        }
        brainSentenceModels.add(brainSentenceModel);
    }

    public List<BrainSentenceModel> getBrainSentenceModels() {
        return brainSentenceModels;
    }

    public void setBrainSentenceModels(List<BrainSentenceModel> brainSentenceModels) {
        this.brainSentenceModels = brainSentenceModels;
    }

    private List<BrainMeanModel> brainMeanModels;

    public void addBrainMeanModel(BrainMeanModel brainMeanModel){
        if(brainMeanModels==null){
            brainMeanModels = new ArrayList<BrainMeanModel>();
        }
        brainMeanModels.add(brainMeanModel);
    }

    public List<BrainMeanModel> getBrainMeanModels() {
        return brainMeanModels;
    }

    public void setBrainMeanModels(List<BrainMeanModel> brainMeanModels) {
        this.brainMeanModels = brainMeanModels;
    }



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brain_words
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.ID
     *
     * @return the value of brain_words.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.ID
     *
     * @param id the value for brain_words.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.word
     *
     * @return the value of brain_words.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.word
     *
     * @param word the value for brain_words.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.exchange
     *
     * @return the value of brain_words.exchange
     *
     * @mbggenerated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.exchange
     *
     * @param exchange the value for brain_words.exchange
     *
     * @mbggenerated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.voice
     *
     * @return the value of brain_words.voice
     *
     * @mbggenerated
     */
    public String getVoice() {
        return voice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.voice
     *
     * @param voice the value for brain_words.voice
     *
     * @mbggenerated
     */
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.times
     *
     * @return the value of brain_words.times
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.times
     *
     * @param times the value for brain_words.times
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.cet4
     *
     * @return the value of brain_words.cet4
     *
     * @mbggenerated
     */
    public Integer getCet4() {
        return cet4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.cet4
     *
     * @param cet4 the value for brain_words.cet4
     *
     * @mbggenerated
     */
    public void setCet4(Integer cet4) {
        this.cet4 = cet4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.cet6
     *
     * @return the value of brain_words.cet6
     *
     * @mbggenerated
     */
    public Integer getCet6() {
        return cet6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.cet6
     *
     * @param cet6 the value for brain_words.cet6
     *
     * @mbggenerated
     */
    public void setCet6(Integer cet6) {
        this.cet6 = cet6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_words.gre
     *
     * @return the value of brain_words.gre
     *
     * @mbggenerated
     */
    public Integer getGre() {
        return gre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_words.gre
     *
     * @param gre the value for brain_words.gre
     *
     * @mbggenerated
     */
    public void setGre(Integer gre) {
        this.gre = gre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_words
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrainWordModel other = (BrainWordModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWord() == null ? other.getWord() == null : this.getWord().equals(other.getWord()))
            && (this.getExchange() == null ? other.getExchange() == null : this.getExchange().equals(other.getExchange()))
            && (this.getVoice() == null ? other.getVoice() == null : this.getVoice().equals(other.getVoice()))
            && (this.getTimes() == null ? other.getTimes() == null : this.getTimes().equals(other.getTimes()))
            && (this.getCet4() == null ? other.getCet4() == null : this.getCet4().equals(other.getCet4()))
            && (this.getCet6() == null ? other.getCet6() == null : this.getCet6().equals(other.getCet6()))
            && (this.getGre() == null ? other.getGre() == null : this.getGre().equals(other.getGre()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_words
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWord() == null) ? 0 : getWord().hashCode());
        result = prime * result + ((getExchange() == null) ? 0 : getExchange().hashCode());
        result = prime * result + ((getVoice() == null) ? 0 : getVoice().hashCode());
        result = prime * result + ((getTimes() == null) ? 0 : getTimes().hashCode());
        result = prime * result + ((getCet4() == null) ? 0 : getCet4().hashCode());
        result = prime * result + ((getCet6() == null) ? 0 : getCet6().hashCode());
        result = prime * result + ((getGre() == null) ? 0 : getGre().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_words
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", word=").append(word);
        sb.append(", exchange=").append(exchange);
        sb.append(", voice=").append(voice);
        sb.append(", times=").append(times);
        sb.append(", cet4=").append(cet4);
        sb.append(", cet6=").append(cet6);
        sb.append(", gre=").append(gre);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}