package com.prince.myproj.brain.models;

import java.io.Serializable;

public class BrainMeanModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_means.wordID
     *
     * @mbggenerated
     */
    private Integer wordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_means.posID
     *
     * @mbggenerated
     */
    private Integer posid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_means.means
     *
     * @mbggenerated
     */
    private String means;

    private BrainPosModel brainPosModel;

    public BrainPosModel getBrainPosModel() {
        return brainPosModel;
    }

    public void setBrainPosModel(BrainPosModel brainPosModel) {
        this.brainPosModel = brainPosModel;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brain_means
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_means.wordID
     *
     * @return the value of brain_means.wordID
     *
     * @mbggenerated
     */
    public Integer getWordid() {
        return wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_means.wordID
     *
     * @param wordid the value for brain_means.wordID
     *
     * @mbggenerated
     */
    public void setWordid(Integer wordid) {
        this.wordid = wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_means.posID
     *
     * @return the value of brain_means.posID
     *
     * @mbggenerated
     */
    public Integer getPosid() {
        return posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_means.posID
     *
     * @param posid the value for brain_means.posID
     *
     * @mbggenerated
     */
    public void setPosid(Integer posid) {
        this.posid = posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_means.means
     *
     * @return the value of brain_means.means
     *
     * @mbggenerated
     */
    public String getMeans() {
        return means;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_means.means
     *
     * @param means the value for brain_means.means
     *
     * @mbggenerated
     */
    public void setMeans(String means) {
        this.means = means == null ? null : means.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_means
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrainMeanModel other = (BrainMeanModel) that;
        return (this.getWordid() == null ? other.getWordid() == null : this.getWordid().equals(other.getWordid()))
            && (this.getPosid() == null ? other.getPosid() == null : this.getPosid().equals(other.getPosid()))
            && (this.getMeans() == null ? other.getMeans() == null : this.getMeans().equals(other.getMeans()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_means
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWordid() == null) ? 0 : getWordid().hashCode());
        result = prime * result + ((getPosid() == null) ? 0 : getPosid().hashCode());
        result = prime * result + ((getMeans() == null) ? 0 : getMeans().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_means
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wordid=").append(wordid);
        sb.append(", posid=").append(posid);
        sb.append(", means=").append(means);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}