package com.prince.myproj.brain.models;

import java.io.Serializable;

public class BrainPosModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_pos.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_pos.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_pos.means
     *
     * @mbggenerated
     */
    private String means;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_pos.ID
     *
     * @return the value of brain_pos.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_pos.ID
     *
     * @param id the value for brain_pos.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_pos.name
     *
     * @return the value of brain_pos.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_pos.name
     *
     * @param name the value for brain_pos.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_pos.means
     *
     * @return the value of brain_pos.means
     *
     * @mbggenerated
     */
    public String getMeans() {
        return means;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_pos.means
     *
     * @param means the value for brain_pos.means
     *
     * @mbggenerated
     */
    public void setMeans(String means) {
        this.means = means == null ? null : means.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrainPosModel other = (BrainPosModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMeans() == null ? other.getMeans() == null : this.getMeans().equals(other.getMeans()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMeans() == null) ? 0 : getMeans().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", means=").append(means);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}