package com.prince.myproj.brain.models;

import java.io.Serializable;
import java.util.Date;

public class BrainWordCollectModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_collect.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_collect.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_collect.word_id
     *
     * @mbggenerated
     */
    private Integer wordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_collect.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brain_word_collect.is_alive
     *
     * @mbggenerated
     */
    private Integer isAlive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_collect.id
     *
     * @return the value of brain_word_collect.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_collect.id
     *
     * @param id the value for brain_word_collect.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_collect.open_id
     *
     * @return the value of brain_word_collect.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_collect.open_id
     *
     * @param openId the value for brain_word_collect.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_collect.word_id
     *
     * @return the value of brain_word_collect.word_id
     *
     * @mbggenerated
     */
    public Integer getWordId() {
        return wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_collect.word_id
     *
     * @param wordId the value for brain_word_collect.word_id
     *
     * @mbggenerated
     */
    public void setWordId(Integer wordId) {
        this.wordId = wordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_collect.create_time
     *
     * @return the value of brain_word_collect.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_collect.create_time
     *
     * @param createTime the value for brain_word_collect.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brain_word_collect.is_alive
     *
     * @return the value of brain_word_collect.is_alive
     *
     * @mbggenerated
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brain_word_collect.is_alive
     *
     * @param isAlive the value for brain_word_collect.is_alive
     *
     * @mbggenerated
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BrainWordCollectModel other = (BrainWordCollectModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getWordId() == null ? other.getWordId() == null : this.getWordId().equals(other.getWordId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getIsAlive() == null ? other.getIsAlive() == null : this.getIsAlive().equals(other.getIsAlive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getWordId() == null) ? 0 : getWordId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsAlive() == null) ? 0 : getIsAlive().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", openId=").append(openId);
        sb.append(", wordId=").append(wordId);
        sb.append(", createTime=").append(createTime);
        sb.append(", isAlive=").append(isAlive);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}