package com.prince.myproj.brain.dao;

import com.prince.myproj.brain.models.BrainSentenceModel;
import com.prince.myproj.brain.models.BrainWordModel;

import java.util.List;

public interface BrainSentenceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    int insert(BrainSentenceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    int insertSelective(BrainSentenceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    BrainSentenceModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrainSentenceModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_sentence
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrainSentenceModel record);

    List<BrainSentenceModel> selectSentencesWithWords(List<BrainWordModel> brainWordModels);
}