package com.prince.myproj.brain.dao;

import com.prince.myproj.brain.models.BrainEnergyModel;

import java.util.List;

public interface BrainEnergyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_energy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_energy
     *
     * @mbggenerated
     */
    int insert(BrainEnergyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_energy
     *
     * @mbggenerated
     */
    int insertSelective(BrainEnergyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_energy
     *
     * @mbggenerated
     */
    BrainEnergyModel selectByPrimaryKey(Long id);

    List<BrainEnergyModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_energy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrainEnergyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_energy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrainEnergyModel record);
}