package com.prince.myproj.brain.dao;

import com.prince.myproj.brain.models.BrainMeanModel;
import com.prince.myproj.brain.models.BrainWordModel;

import java.util.List;

public interface BrainMeanModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_means
     *
     * @mbggenerated
     */
    int insert(BrainMeanModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_means
     *
     * @mbggenerated
     */
    int insertSelective(BrainMeanModel record);

    List<BrainMeanModel> selectByWordList(List<BrainWordModel> brainWordModels);
}