package com.prince.myproj.brain.dao;

import com.prince.myproj.brain.models.BrainWordCollectModel;

import java.util.List;

public interface BrainWordCollectModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    int insert(BrainWordCollectModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    int insertSelective(BrainWordCollectModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    BrainWordCollectModel selectByPrimaryKey(Long id);

    BrainWordCollectModel selectByOpenIdAndWordId(BrainWordCollectModel record);

    List<BrainWordCollectModel> selectByOpenId(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrainWordCollectModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrainWordCollectModel record);
}