package com.prince.myproj.brain.dao;

import com.prince.myproj.brain.models.BrainPosModel;
import com.prince.myproj.brain.models.BrainWordModel;

import java.util.List;

public interface BrainPosModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    int insert(BrainPosModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    int insertSelective(BrainPosModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    BrainPosModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrainPosModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_pos
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrainPosModel record);

    List<BrainPosModel> selectByWordList(List<BrainWordModel> brainWordModels);
}