package com.prince.myproj.brain.dao;

import com.prince.myproj.brain.models.BrainWordRecordModel;

public interface BrainWordRecordModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    int insert(BrainWordRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    int insertSelective(BrainWordRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    BrainWordRecordModel selectByPrimaryKey(Long id);

    BrainWordRecordModel selectByOpenId(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BrainWordRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brain_word_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BrainWordRecordModel record);
}